### ISSUE TITLE
gzip error

### ISSUE THREAD

**Issue by farnsworthd** [Nusob888/fasterqParseR#5]
Not sure why fasterqParseR would expect gzip files...
Here I am pointing to fasterq-dump output of 3 spit fastq files and get the following error when I run:
assigned_files <- assignSRAreads(working_dir = working_dir, input_dir = input_dir, outdir = outdir, parallel=TRUE)
[1] "First n=250 read lengths will be output into outdir"

gzip: /{path}//SRR12661516_1.fastq: not in gzip format

**Comment by Nusob888** [comment]
Hi, 

Thanks for the interest in using the tool and for pointing this out. 

Should be sorted now. Please have another try and let me know the outcome.

**Comment by Nusob888** [comment]
Closed as no reply. Changes were benchmarked and should handle non zipped input
