### ISSUE TITLE
Item 1 of input is not a data.frame, data.table or list

### ISSUE THREAD

**Issue by Diennguyen8290** [Nusob888/fasterqParseR#6]
Hi,

Thanks for developing the tool.

I've used it for GSE189539 dataset (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE189539) and run into an error at the assignSRAread() step as follow:

[1] "First n=250 read lengths will be output into outdir"
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
sh: NA: command not found
Error in data.table::rbindlist(assigned_SRA) :
  Item 1 of input is not a data.frame, data.table or list
In addition: Warning message:
In mclapply(toParse$fasterq_list, function(x) { :
  all scheduled cores encountered errors in user code

The output of traceback():

2: data.table::rbindlist(assigned_SRA)
1: assignSRAreads(working_dir = working_dir, input_dir = input_dir,
       outdir = outdir, parallel = TRUE)

Please help me have a look.

Thanks,
Dien

**Comment by Nusob888** [comment]
Hi,

I have checked. All seems to be working fine.

Can you try with raw SRA file names? e.g. SRR1234567_1.fastq.gz, SRR1234567_2.fastq.gz

If that doesn't work please screenshot your working directory structure.

Thanks!

**Comment by Diennguyen8290** [comment]
Thanks, Bo,

I did try with those raw SRA file names (both rename old files and redownload new ones) but it still doesn't work.

I'm working on supercomputer, please find enclosed screenshot of the scripts I've been using.

<img width="1106" alt="Screenshot 2022-01-30 at 07 07 22" src="https://user-images.githubusercontent.com/60179011/151690348-dbbf4a25-5a5f-486a-b0b1-da12988b1c45.png">

Of course the raw SRA fastq files are in _fasterq_output_ folder and _read_lengths_ folder has been created.

Many thanks,
Dien

**Comment by Nusob888** [comment]
Hi I have tested it on one of the SRA runs you supplied. It works on my side. 

can you try reinstall it?

It looks like when you run it, you may not have the right permissions? the sh:NA: no command found 

suggests that when you are running system() calls via R, it doesn't seem to recognise it. Can you manually try and run a simple system() call?

e.g. system(paste0("mkdir ", working_dir, " test"))

Other that this, I can't seem to reproduce the errors. Again, feel free to email me on bo.sun@well.ox.ac.uk


![test_fasterqparser](https://user-images.githubusercontent.com/59517563/151694749-ba3be987-3ca7-4723-9835-9bf883a635bf.png)

**Comment by Nusob888** [comment]
Ok, so problem isolated. It appears to be an issue caused by upgrading to R version 4. The resulting effect is that data frame vectors were no longer able to be called directly without grepl(). Now updated, and should work. 

Please confirm if working and thanks so much for spotting this!

**Comment by Diennguyen8290** [comment]
It works nicely for now. 

Many thanks, Bo.

Best,
Dien
