### ISSUE TITLE
cannot open file '/SRR9951080_split/assigned_SRAreads.csv': No such file or directory

### ISSUE THREAD

**Issue by BirongZhang** [Nusob888/fasterqParseR#7]
Hi Bo,

Thanks for sharing this amazing package! Very helpful!

I have a little problem about the last step.  Even if I encounter an error, I still get new fastq data that I can use for further analysis. I was wondering if you could take a look at it, so it could help me make the process go more smoothly.

Here is the error for the last step renameAll(assigned_SRA= as...):
```
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/scratch/c.c2050857/GSE135710/SRR9951080_split/assigned_SRAreads.csv': No such file or directory
```

Here is my script: 
```
## select
  working_directory = "/scratch/c.c2050857/GSE135710/"
a=list.files("/scratch/c.c2050857/GSE135710/raw_data/")

for (i in a ){ 
  split <- paste("/scratch/c.c2050857/GSE135710/split_data/",i,sep="")
  dir.create(split) 
  input_directory = paste("/scratch/c.c2050857/GSE135710/raw_data/",i,"/",sep="")
  output_directory = split

  assigned_files <- assignSRAreads(working_dir = working_directory, input_dir = input_directory, outdir =output_directory, parallel=TRUE)

  renameAll(assigned_SRA= assigned_files, input_dir=input_directory, format="cellranger")
}
```

Any advices would be highly appreciated! Thanks!

Kind regards,
Birong

**Comment by Nusob888** [comment]
Hi, 
I am glad the tool is useful for you. 

I am a little confused by your script. Can you show me what the file directories look like in your listed paths? The tool does not need to have SRAXXX_1, SRAXXX_2 or SRAXXX_3 files to be split. It will handle them as they are, you only need to provide it with the input directory. 

Similarly, your output directory can be a single directory. This is just where it saves the mean read lengths. 

I would advise making a copy of your directory for testing and try the below code

`
##Assign directories
working_directory = "/scratch/c.c2050857/GSE135710/"
input_dir = "/scratch/c.c2050857/GSE135710/raw_data/"
outdir="/scratch/c.c2050857/GSE135710/read_lengths/" #you will need to create this directory

##Assign SRA reads.

assigned_files <- assignSRAreads(working_dir = working_directory, input_dir = input_dir, outdir =outdir)

##I would at this point inspect the assignments
head(assigned_files)

##Then rename
renameAll(assigned_SRA= assigned_files, input_dir=input_dir, format="cellranger")
`

**Comment by BirongZhang** [comment]
Hi Bo,

Thanks for your effective reply.

Your suggestion solved the problem perfectly. I don't need to write a loop, you package can run it automatically.

Brilliant work!  👍

Best,
Birong

**Comment by Nusob888** [comment]
Great news! Glad you enjoy the package

**Comment by Nusob888** [comment]
Great news!
